// <auto-generated />
using System;
using BankAccountingSystem.WebApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BankAccountingSystem.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250501170612_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BankAccountingSystem.WebApp.Models.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("AccountType")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("NormalBalance")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Accounts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccountNumber = "1010",
                            AccountType = 0,
                            IsActive = true,
                            Name = "Cash",
                            NormalBalance = 0
                        },
                        new
                        {
                            Id = 2,
                            AccountNumber = "1210",
                            AccountType = 0,
                            IsActive = true,
                            Name = "Accounts Receivable",
                            NormalBalance = 0
                        },
                        new
                        {
                            Id = 3,
                            AccountNumber = "2010",
                            AccountType = 1,
                            IsActive = true,
                            Name = "Accounts Payable",
                            NormalBalance = 1
                        },
                        new
                        {
                            Id = 4,
                            AccountNumber = "3010",
                            AccountType = 2,
                            IsActive = true,
                            Name = "Common Stock",
                            NormalBalance = 1
                        },
                        new
                        {
                            Id = 5,
                            AccountNumber = "4010",
                            AccountType = 3,
                            IsActive = true,
                            Name = "Service Revenue",
                            NormalBalance = 1
                        },
                        new
                        {
                            Id = 6,
                            AccountNumber = "5010",
                            AccountType = 4,
                            IsActive = true,
                            Name = "Rent Expense",
                            NormalBalance = 0
                        });
                });

            modelBuilder.Entity("BankAccountingSystem.WebApp.Models.JournalEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime>("EntryDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsPosted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("PostedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReferenceNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("JournalEntries");
                });

            modelBuilder.Entity("BankAccountingSystem.WebApp.Models.JournalEntryLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.Property<decimal>("CreditAmount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("DebitAmount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("JournalEntryId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("JournalEntryId");

                    b.ToTable("JournalEntryLines");
                });

            modelBuilder.Entity("BankAccountingSystem.WebApp.Models.JournalEntryLine", b =>
                {
                    b.HasOne("BankAccountingSystem.WebApp.Models.Account", "Account")
                        .WithMany("JournalEntryLines")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BankAccountingSystem.WebApp.Models.JournalEntry", "JournalEntry")
                        .WithMany("Lines")
                        .HasForeignKey("JournalEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("JournalEntry");
                });

            modelBuilder.Entity("BankAccountingSystem.WebApp.Models.Account", b =>
                {
                    b.Navigation("JournalEntryLines");
                });

            modelBuilder.Entity("BankAccountingSystem.WebApp.Models.JournalEntry", b =>
                {
                    b.Navigation("Lines");
                });
#pragma warning restore 612, 618
        }
    }
}
